### ISSUE TITLE
Module has dependency on 2.1.x so breaks on 2.0.x

### ISSUE THREAD

**Issue by redboxmarcins** [CKOTech/checkout-magento2-plugin#3]
Hi
Below files do not exist in 2.0.x
Magento_Checkout/js/action/redirect-on-success.js
Magento_Checkout/js/model/place-order.js

Those were introduced in 2.1.x

Is your module compatible with 2.0.x? If not please correct your composer.json to not allow installation on 2.0.x

Do you have version of the module which works on 2.0.x?

**Comment by nicolas-maalouf-cko** [comment]
@mage2pro can you please assist us on this?

Getting the below error on 2.0.7 when going to payment selection in checkout:

require.js:166 Uncaught Error: Script error for: Magento_Checkout/js/model/place-order
http://requirejs.org/docs/errors.html#scripterror

**Comment by mage2pro** [comment]
I have fixed it in the [1.0.8](https://github.com/CKOTech/checkout-magento2-plugin/releases/tag/1.0.8) version.

**Comment by redboxmarcins** [comment]
Payment method is visible in the checkout but after placing order there is error


```
{
    "message": "\u00abDfe\\CheckoutCom\\Charge\u00bb: \u0437\u043d\u0430\u0447\u0435\u043d\u0438\u0435 \u00abNULL\u00bb \u043d\u0435\u0434\u043e\u043f\u0443\u0441\u0442\u0438\u043c\u043e \u0434\u043b\u044f \u0441\u0432\u043e\u0439\u0441\u0442\u0432\u0430 \u00abtoken\u00bb.\n\u0421\u043e\u043e\u0431\u0449\u0435\u043d\u0438\u0435 \u043f\u0440\u043e\u0432\u0435\u0440\u044f\u044e\u0449\u0435\u0433\u043e:\n\u0421\u0438\u0441\u0442\u0435\u043c\u0430 \u0432\u043c\u0435\u0441\u0442\u043e \u043d\u0435\u043f\u0443\u0441\u0442\u043e\u0439 \u0441\u0442\u0440\u043e\u043a\u0438 \u043f\u043e\u043b\u0443\u0447\u0438\u043b\u0430 \u00abNULL\u00bb.",
    "trace": "#0 \/var\/www\/magento\/vendor\/mage2pro\/checkout.com\/Method.php(606): df_le(Object(Df\\Core\\Exception\\InvalidObjectProperty))\n#1 \/var\/www\/magento\/vendor\/mage2pro\/checkout.com\/Method.php(691): Dfe\\CheckoutCom\\Method->leh(Object(Closure))\n#2 \/var\/www\/magento\/vendor\/mage2pro\/checkout.com\/Method.php(632): Dfe\\CheckoutCom\\Method->response()\n#3 \/var\/www\/magento\/vendor\/mage2pro\/checkout.com\/Method.php(652): Dfe\\CheckoutCom\\Method->r()\n#4 \/var\/www\/magento\/vendor\/mage2pro\/checkout.com\/Method.php(216): Dfe\\CheckoutCom\\Method->redirectUrl()\n#5 \/var\/www\/magento\/vendor\/magento\/module-sales\/Model\/Order\/Payment.php(322): Dfe\\CheckoutCom\\Method->getConfigPaymentAction()\n#6 \/var\/www\/magento\/var\/generation\/Magento\/Sales\/Model\/Order\/Payment\/Interceptor.php(154): Magento\\Sales\\Model\\Order\\Payment->place()\n#7 \/var\/www\/magento\/vendor\/magento\/module-sales\/Model\/Order.php(871): Magento\\Sales\\Model\\Order\\Payment\\Interceptor->place()\n#8 \/var\/www\/magento\/vendor\/magento\/module-sales\/Model\/Order.php(1060): Magento\\Sales\\Model\\Order->_placePayment()\n#9 \/var\/www\/magento\/var\/generation\/Magento\/Sales\/Model\/Order\/Interceptor.php(479): Magento\\Sales\\Model\\Order->place()\n#10 \/var\/www\/magento\/vendor\/magento\/module-sales\/Model\/Service\/OrderService.php(190): Magento\\Sales\\Model\\Order\\Interceptor->place()\n#11 \/var\/www\/magento\/vendor\/magento\/module-quote\/Model\/QuoteManagement.php(491): Magento\\Sales\\Model\\Service\\OrderService->place(Object(Magento\\Sales\\Model\\Order\\Interceptor))\n#12 \/var\/www\/magento\/vendor\/magento\/module-quote\/Model\/QuoteManagement.php(394): Magento\\Quote\\Model\\QuoteManagement->submitQuote(Object(Magento\\Quote\\Model\\Quote\\Interceptor), Array)\n#13 \/var\/www\/magento\/vendor\/magento\/module-quote\/Model\/QuoteManagement.php(354): Magento\\Quote\\Model\\QuoteManagement->submit(Object(Magento\\Quote\\Model\\Quote\\Interceptor))\n#14 \/var\/www\/magento\/vendor\/magento\/module-quote\/Model\/GuestCart\/GuestCartManagement.php(87): Magento\\Quote\\Model\\QuoteManagement->placeOrder('436', NULL)\n#15 \/var\/www\/magento\/vendor\/magento\/module-checkout\/Model\/GuestPaymentInformationManagement.php(79): Magento\\Quote\\Model\\GuestCart\\GuestCartManagement->placeOrder('f605d8ed1561870...')\n#16 \/var\/www\/magento\/vendor\/mage2pro\/checkout.com\/PlaceOrder.php(29): Magento\\Checkout\\Model\\GuestPaymentInformationManagement->savePaymentInformationAndPlaceOrder('f605d8ed1561870...', 'tester@test1.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#17 [internal function]: Dfe\\CheckoutCom\\PlaceOrder->guest('f605d8ed1561870...', 'tester@test1.co...', Object(Magento\\Quote\\Model\\Quote\\Payment\\Interceptor), Object(Magento\\Quote\\Model\\Quote\\Address\\Interceptor))\n#18 \/var\/www\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(265): call_user_func_array(Array, Array)\n#19 \/var\/www\/magento\/vendor\/magento\/module-webapi\/Controller\/Rest.php(160): Magento\\Webapi\\Controller\\Rest->processApiRequest()\n#20 \/var\/www\/magento\/var\/generation\/Magento\/Webapi\/Controller\/Rest\/Interceptor.php(24): Magento\\Webapi\\Controller\\Rest->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#21 \/var\/www\/magento\/vendor\/magento\/framework\/App\/Http.php(115): Magento\\Webapi\\Controller\\Rest\\Interceptor->dispatch(Object(Magento\\Framework\\App\\Request\\Http))\n#22 \/var\/www\/magento\/vendor\/magento\/framework\/App\/Bootstrap.php(258): Magento\\Framework\\App\\Http->launch()\n#23 \/var\/www\/magento\/pub\/index.php(37): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#24 {main}"
```

**Comment by mage2pro** [comment]
This problem is not related to the topic.
1. Create a separate topic for this problem.
- Provide me the SSH access to your server, and I will debug this problem.

**Comment by redboxmarcins** [comment]
@mage2pro our infosec policy does not allow 3rd party SSH access
Can you think of about any other alternative?

Maybe it is misconfiguration on our side?

**Comment by mage2pro** [comment]
Try to reproduce it in a less secure environment (on a test server), and provide an SSH access to it.

**Comment by mage2pro** [comment]
Or maybe @nicolas-maalouf-cko could reproduce it on his Amazon EC2 test instance?
I am unable to reproduce it.
Anyway, it is not related to the topic, create a new topic for the issue.

**Comment by nicolas-maalouf-cko** [comment]
This is not happening on my instance with 2.0.7. 

Normal orders go through properly.
